language: php
php:
  - '7.2.15'
before_script:
  - cp application/config/database.example.php application/config/database.php
  - cp application/config/secrets.example.php application/config/secrets.php
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('sharifjudge') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql -e 'CREATE DATABASE sharifjudge;'
  - composer install
services:
  -mysql
script: php index.php RunTest